/**
 * BOQ domain types.
 *
 * This file defines shared interfaces for BOQ rows, units, and rule outputs
 * used by `boq`, `quantity`, `verification`, and `export` modules.
 */

export interface BoqLineItem {
  /** Stable row identifier in a job context. */
  id: string;
  /** Human-readable item description (Thai/English). */
  description: string;
  /** Measurement unit, e.g. m, m2, m3, set, point. */
  unit: string;
  /** Calculated or extracted quantity value. */
  quantity: number;
}

export interface BoqDocument {
  /** Job identifier that produced this BOQ payload. */
  jobId: string;
  /** BOQ line items generated by rule + quantity engines. */
  items: BoqLineItem[];
}
